name: Render and Push CV

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  render-and-push:
    if: "!contains(github.actor, '[bot]')"  # Skip if commit made by any bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install RenderCV
        run: pip install -r requirements.txt

      - name: RenderCV
        run: |
          cd src
          cv_file=$(find . -maxdepth 1 -type f -name "*.yaml" | head -n 1)
          if [ -z "$cv_file" ]; then
            echo "No YAML file found in ./src"
            exit 1
          fi
          cd ..
          rendercv render src/$cv_file --output-folder-name src --pdf-path public/Resume.pdf

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src public/Resume.pdf
          if ! git diff --cached --quiet; then
            git commit -m "Auto update generated CV files [skip ci]"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi
