name: Render a CV

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  rendercv:
    name: RenderCV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install RenderCV
        run: |
          pip install -r requirements.txt

      - name: RenderCV with outputs to src and PDF to public
        run: |
          cd target
          cv_file=$(find . -maxdepth 1 -type f -name "*.yaml" | head -n 1)
          if [ -z "$cv_file" ]; then
            echo "No YAML file found in ./target"
            exit 1
          fi
          cd ..
          mkdir -p public
          rendercv render target/$cv_file --output-folder-name src --pdf-path ./public/Resume.pdf

      - name: Upload artifact with all outputs
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: |
            src
            public/Resume.pdf

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            cv:
              - 'target/*.yaml'
              - 'src/**'
              - 'public/Resume.pdf'
