name: Render a CV

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  rendercv:
    name: RenderCV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install RenderCV
        run: |
          pip install -r requirements.txt

      - name: RenderCV from YAML
        run: |
          cd target
          cv_file=$(find . -maxdepth 1 -type f -name "*_CV.yaml" | head -n 1)
          if [ -z "$cv_file" ]; then
            echo "No RenderCV YAML file found in ./target"
            exit 1
          fi
          cd ..
          mkdir -p ./public
          rendercv render target/$cv_file --pdf-path ./public/Resume.pdf --typst-path ./public/${cv_file%.yaml}.typ

      - name: Upload rendercv_output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: ./public

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            cv:
              - 'target/*_CV.yaml'
              - 'public/*.typ'
